server:
  port: ${PORT:8080}


#spring:
spring:
  application:
    name: ms-buscador
  jpa:
    database: MYSQL
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/safepeople_buscador
    username: ${DB_USER:root}
    password: ${DB_PASS:Server01$}  #cambiar clave

  batch:
    jdbc:
      initialize-schema: always
  sql:
    init:
      platform: mysql
      mode: always

## Classic Eureka configuration
eureka:
  instance:
    preferIpAddress: true
    non-secure-port-enabled: true
    secure-port-enabled: false
    non-secure-port: ${server.port}
    secure-port: 443
    hostname: ${HOSTNAME:localhost}

  client:
    registerWithEureka: true
    fetchRegistry: true
    hostname: ms-buscador
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}